### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by jwombat** [IBM/Watson-Unity-ARKit#5]
I've tried every possible combination of every value available from my Dashboard. They 100% return some kind of authentication error. However, the template "curl" command found elsewhere in the documentation works, which I take to mean that I have the proper service set up, so it's only through Unity that there's a problem. Do you have ANY concrete examples of which values to fill into the StreamingSpeech gameobject to get it to work?

**Comment by akeller** [comment]
You need to provide either username/password or an api key for each service. Are you having trouble with all the services or just speech to text?

**Comment by akeller** [comment]
![image](https://user-images.githubusercontent.com/1051363/52025689-e7a73700-24ca-11e9-95ba-9287b5de03d9.png)

My test app includes my older services, all of which still have username/password for auth. You can see the red markout where I have provided each. I believe each URL for the services defaults to the Dallas region, so if your services are in another region, you may need to check the documentation and change the URLs. What region are your services in?

**Comment by jwombat** [comment]
Speech to Text works. There’s a sample curl command in my dashboard that executes with no problem.

The Unity vr-speech-sandbox project is what doesn’t work. A big part of the problem is that it asks for a bunch of credentials for CF authentication in multiple places, and there’s nothing anywhere in my dashboard called CF. There’s nothing called IAM either.  I’m following the instructions in the readme that came with the project, and it doesn’t give any indication of where to find this data. In fact, it doesn’t agree with the image you sent me either (thanks for that image, it helped a bit). So overall the question is where to find the data that the Unity project wants in order to execute.

Thanks.
—julian

**Comment by akeller** [comment]
Ah, ok. Next time please open an issue on the vr-speech-sandbox project as this one is completely separate. 

IAM is the same as API key. If you don't see CF on your dashboard, you are using IAM/API key/token authentication. Sorry for the confusion, we are in a transition period where we have some users with older service that have to connecting using CF username/password.

For you, you should see you API key information on the service page. Depending on where your service is (what region its in) you may need to change the service endpoint: https://cloud.ibm.com/apidocs/speech-to-text#service-endpoint

My image above shows CF authentication.

**Comment by akeller** [comment]
Which repo are you using? Or did you pull in vr-speech-sandbox when it was still in the asset store? Here is a link with buttons to all the repos: https://developer.ibm.com/patterns/create-a-virtual-reality-speech-sandbox/

If you let us know which one you are using, we can update the readme to be clearly about authentication. 

CC @scottdangelo

**Comment by jwombat** [comment]
Yes, that’s the one, specifically the Cardboard version. At first I was using the Asset Store copy, but replaced that with a direct download on Tuesday.

Below is the window that I see in Unity. There are two IAM sections for this gameobject. It looks to me like the first set should come from my Speech to Text service, and the second set should come from my Watson Assistant service. Doing that consistently results in a 401-Unauthorized. The frustrating thing is that when I use a curl command in a shell with the same credentials it works no problem.

I’m accessing the Dallas services.

**Comment by scottdangelo** [comment]
@jwombat I'll test this to see if I can reproduce.
In the meantime, can we move this conversation to:
https://github.com/IBM/vr-speech-sandbox-cardboard/issues

**Comment by scottdangelo** [comment]
Closing this issue. Moved to https://github.com/IBM/vr-speech-sandbox-cardboard/issues/55 .
