### ISSUE TITLE
Readme error in "Building and Running"

### ISSUE THREAD

**Issue by jazzymcgee** [IBM/Watson-Unity-ARKit#7]
1. Open Unity and inside the project launcher select the Open button.

2. Navigate to where you cloned this repository and open the **Creation Sandbox** directory.

In neither the Unity SDK repo (in both develop and master branches) does "Creation Sandbox" appear to exist, this is the same case for this repo as well. Did you mean we should create a directory called Creation Sandbox first? And if so, at what level and where would we create it? (I am on the most up to date version of the Unity SDK repo)

**Comment by stevemar** [comment]
Poke @akeller

**Comment by akeller** [comment]
Looks like a C&P issue on my part from the template repo I was following. I'll remove that line.

**Comment by akeller** [comment]
@jazzymcgee I've removed that line from the repo. No action on your part! Thanks for the heads up.

**Comment by stevemar** [comment]
Looks like this is resolved. THanks @akeller ! 

@jazzymcgee that step is not required.
